#############################################################################
# Makefile for building: phototonic
# Generated by qmake (2.01a) (Qt 4.8.5) on: Tue Jan 21 21:12:19 2014
# Project:  phototonic.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile phototonic.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -g -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = dialogs.cpp \
		main.cpp \
		mainwindow.cpp \
		thumbview.cpp \
		imageview.cpp \
		global.cpp moc_dialogs.cpp \
		moc_mainwindow.cpp \
		moc_thumbview.cpp \
		moc_imageview.cpp \
		qrc_phototonic.cpp
OBJECTS       = dialogs.o \
		main.o \
		mainwindow.o \
		thumbview.o \
		imageview.o \
		global.o \
		moc_dialogs.o \
		moc_mainwindow.o \
		moc_thumbview.o \
		moc_imageview.o \
		qrc_phototonic.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		phototonic.pro
QMAKE_TARGET  = phototonic
DESTDIR       = 
TARGET        = phototonic

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: phototonic.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile phototonic.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile phototonic.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/phototonic1.0.0 || $(MKDIR) .tmp/phototonic1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/phototonic1.0.0/ && $(COPY_FILE) --parents dialogs.h mainwindow.h thumbview.h imageview.h global.h .tmp/phototonic1.0.0/ && $(COPY_FILE) --parents phototonic.qrc .tmp/phototonic1.0.0/ && $(COPY_FILE) --parents dialogs.cpp main.cpp mainwindow.cpp thumbview.cpp imageview.cpp global.cpp .tmp/phototonic1.0.0/ && (cd `dirname .tmp/phototonic1.0.0` && $(TAR) phototonic1.0.0.tar phototonic1.0.0 && $(COMPRESS) phototonic1.0.0.tar) && $(MOVE) `dirname .tmp/phototonic1.0.0`/phototonic1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/phototonic1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_dialogs.cpp moc_mainwindow.cpp moc_thumbview.cpp moc_imageview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialogs.cpp moc_mainwindow.cpp moc_thumbview.cpp moc_imageview.cpp
moc_dialogs.cpp: thumbview.h \
		dialogs.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) dialogs.h -o moc_dialogs.cpp

moc_mainwindow.cpp: thumbview.h \
		imageview.h \
		mainwindow.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_thumbview.cpp: thumbview.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) thumbview.h -o moc_thumbview.cpp

moc_imageview.cpp: imageview.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) imageview.h -o moc_imageview.cpp

compiler_rcc_make_all: qrc_phototonic.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_phototonic.cpp
qrc_phototonic.cpp: phototonic.qrc \
		images/error_image.png \
		images/about.png \
		images/no_image.png \
		images/next.png \
		images/back.png \
		images/up.png \
		images/delete.png \
		images/cut.png \
		images/copy.png \
		images/zoom_out.png \
		images/paste.png \
		images/phototonic.png \
		images/refresh.png \
		images/home.png \
		images/settings.png \
		images/zoom_in.png \
		images/new_folder.png
	/usr/lib/qt4/bin/rcc -name phototonic phototonic.qrc -o qrc_phototonic.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

dialogs.o: dialogs.cpp dialogs.h \
		thumbview.h \
		global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogs.o dialogs.cpp

main.o: main.cpp mainwindow.h \
		thumbview.h \
		imageview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		thumbview.h \
		imageview.h \
		dialogs.h \
		global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

thumbview.o: thumbview.cpp thumbview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thumbview.o thumbview.cpp

imageview.o: imageview.cpp imageview.h \
		thumbview.h \
		global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageview.o imageview.cpp

global.o: global.cpp global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o global.o global.cpp

moc_dialogs.o: moc_dialogs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogs.o moc_dialogs.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_thumbview.o: moc_thumbview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_thumbview.o moc_thumbview.cpp

moc_imageview.o: moc_imageview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imageview.o moc_imageview.cpp

qrc_phototonic.o: qrc_phototonic.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_phototonic.o qrc_phototonic.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

