######################################################################
# Automatically generated by qmake (3.0) Tue Sep 24 18:38:46 2013
######################################################################

TEMPLATE = app
TARGET = phototonic
INCLUDEPATH += .

# Input
HEADERS += dialogs.h mainwindow.h thumbview.h imageview.h global.h
SOURCES += dialogs.cpp main.cpp mainwindow.cpp thumbview.cpp imageview.cpp global.cpp
RESOURCES += phototonic.qrc
